### ISSUE TITLE
Give indication that "Calculate" button has been pressed

### ISSUE THREAD

**Issue by rkeller6** [astropcr/pmasecapstone#6]
Maybe change color or give a haptic feedback.

**Comment by astropcr** [comment]
Not haptic feedback - cant really do that on desktop PCs. A pop-up would be good with the an error if the result cannot be generated. Otherwise the Word file will open to indicate Calculate Success. This could be an issue down the line if we get much bigger databases and the calculation takes a longer time. Then we may need a spinner of some kind or progress bar.

**Comment by astropcr** [comment]
Added code so that even if no valid arch is found it still opens the report and says no valid options. Only time calc button wont do anything now is if all inputs not selected or when there is exception.
